### ISSUE TITLE
psh - no hosts found

### ISSUE THREAD

**Issue by mdrx-io** [OpenPrograms/payonel-Programs#8]
The OC docs suggest that network cards just automatically expose multiple computers to each other if they are cabled together and each have a card. Yet, when I try to list hosts with `psh`, I get "No hosts found". Am I missing something?

![2017-07-04_13 02 08](https://user-images.githubusercontent.com/955748/27841788-14684e82-60b9-11e7-95ae-b5c3030d5e14.png)
![2017-07-04_13 02 22](https://user-images.githubusercontent.com/955748/27841793-172c076c-60b9-11e7-8f92-98b2b082ebc7.png)

**Comment by payonel** [comment]
This is in need of updating!

**Comment by payonel** [comment]
`psh list` would try to connect to a host with an address `list`, if you want to list available hosts, use `-l` or `--list`

psh has been updated now in oppm. it is fixed and designed for openos 1.7.3

it doesn't have all the features of the old one, but it is more performant and reliable

it current doesnt forward and component api, such as gpu calls. thus it is currently only compatible with strictly io programs. in the future i plan to add a gpu forwarding feature, using `-X` param (like forwarding X over ssh)
