### ISSUE TITLE
Can't get psh working

### ISSUE THREAD

**Issue by Endag** [OpenPrograms/payonel-Programs#9]
Version: "latest" (sorry, no real numbers) installed by oppm (seem to have last commit 5 month ago)
Tested on OC versions: MC1.10.2-1.6.1.6; MC1.10.2-1.6.2.7; MC1.10.2-1.7.0.124;

For OC 1.6.* versions i assumed that required "thread" library is libthread from OPPM's OpenPrograms.ru repo, as it seem to have compatible API unlike Akuukis's thread and there is no another thread library (easy to find at least)
For  OC 1.7 this thread library (or very similar) seems to be built-in.

Symptoms vary:
1) on 1.6 versions rc seems to start pshd but when client  tries to connect says that there is variable "timeouts" in thread library uninitialized.
If i place call to thread.init() in, for ex., checkDaemon function to be initialized at pshd startup then when client tries to connect to host then screen on host resets (like new shell start) and 
client seems to be blocked on "handleNextEvent" call as if it no response from host. On host itself terminal seems to be broken after connect - you can type and run in shell but if you run some program that interacts with terminal itself, like edit, then terminal got scrambled and input to computer completle broken - it ignores even ctrl-alt-c interrupt.

2) on 1.7 version it starts fine, client blocks on connect same way like in 1.6, but on host terminal starts duplicate any input you type (or triplicate if you try co connect again, or quadruplicate if you try even more and so on)

**Comment by payonel** [comment]
openos 1.7.x has threads, those are the threads you should be using
psh has been updated now on oppm, is more efficient than the old version and more reliable
note that it is a strictly io only server, thus programs that read/write directly to the gpu won't work correctly over psh. there are plans to forward gpu (optional arg to psh) in the future
